### ISSUE TITLE
Update Notification Screenshot in README.md

### ISSUE THREAD

**Issue by Abhiroop25902** [dsc-iiest/todo-cli#18]
In #15, we added a new notification icon. This requires update in [README](https://github.com/dsc-iiest/todo-cli/blob/main/README.md) screenshot in Linux and MacOS.

- [x] Update Linux Screenshot in [README](https://github.com/dsc-iiest/todo-cli/blob/main/README.md)
- [ ] #32

**Comment by ethmtrgt** [comment]
Hey, I can work on this. Is that possible to assign me?

**Comment by Abhiroop25902** [comment]
We can try for bundling a customized version of notifier, or we can look for some other Notifier Module

**Comment by Abhiroop25902** [comment]
The second picture looks better. Thanks for your contribution

**Comment by Abhiroop25902** [comment]
Transferring MacOS Notification into a new issue
