### ISSUE TITLE
Add String Based Time Support

### ISSUE THREAD

**Issue by Abhiroop25902** [dsc-iiest/todo-cli#22]
Currently the command to add To-do is as follows
`add 'Todo heading' 'Todo Description' <time in minutes>`

- [ ] We need a way to generalize time to take datetime inputs (not just minute)

Possible Link that may help: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

**Comment by Vipul-Bajaj** [comment]
hi @Abhiroop25902 ,
Can i work on this?

**Comment by Abhiroop25902** [comment]
> You just want to support datetime string or both the datetime and minute. Also, do u have any particular datetime format in mind?

Sorry for the delay, but I had both in mind.....

**Comment by Vipul-Bajaj** [comment]
Can you have a look on the pr once and let me know if the approach for datetime string is right. Meanwhile I will try supporting both
