### ISSUE TITLE
Persistent Todo Storage

### ISSUE THREAD

**Issue by Abhiroop25902** [dsc-iiest/todo-cli#3]
Currently the script saves the to-dos inside the program itself. This means that if the script is closed, all the saved to-dos will be lost.

We need to do the following
- [x] make to-dos save to some file when the script is closed
- [x] make the saved file encrypted so as to avoid leaking of user data

**Comment by Ashish0z** [comment]
HI, I would love to work on this issue.

**Comment by Abhiroop25902** [comment]
sure, assigning this to you then.
If you need any help, feel free to ping here ^_^

**Comment by Abhiroop25902** [comment]
You might want to look in #17. This PR added Interactive CLI, so it could help you define when to trigger Data Storage

**Comment by Ashish0z** [comment]
ok thanks, will do

**Comment by Abhiroop25902** [comment]
hey, it's been 9 days.... is everything alright?
