### ISSUE TITLE
Add Documentation about how to run the script

### ISSUE THREAD

**Issue by Abhiroop25902** [dsc-iiest/todo-cli#5]
Currently the repository does not have any instructions to guide new users to run the script itself. So we need
- [ ] documentation about how to run the script

Running the script as of now is very straight forward, you don't need any pip installs as of now, you just need to write `python3 main.py` to run the script

**Comment by nkhandelwal07** [comment]
So would this task be adding this information the readme.md file? I will submit a pull request for that, but can do something else if necessary.

**Comment by Abhiroop25902** [comment]
yep this one was a small issue, you are free to look into the other issues which are more in-depth

**Comment by Abhiroop25902** [comment]
Issue solved with #8 merged
